# Generated by Django 6.0 on 2026-01-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactAPi',
            new_name='Contact',
        ),
    ]
